.github/workflows/npm-docker-build.yml
=> chore: add comment about why to do this

.github/workflows/npm-build-semantic-version.yml, .github/workflows/npm-build.yml, .github/workflows/npm-codescan-complete.yml, README.md, profile/README.md, workflow-templates/npm-codescan-complete.properties.json, workflow-templates/npm-codescan-complete.yml
* [DEVO-194](https://htw-cloud.atlassian.net/browse/DEVO-194)
=> Devo 194 fix scans

.github/workflows/npm-codescan-complete.yml
=> Pipeline tweaks

.github/workflows/npm-codescan-complete.yml
=> fix: enforce code coverage - sonarcloud

.github/workflows/npm-codescan-complete.yml
* [DEVO-355](https://htw-cloud.atlassian.net/browse/DEVO-355)
=> fix: change default audit arg but allow override

.github/workflows/npm-docker-build.yml
* [DEVO-347](https://htw-cloud.atlassian.net/browse/DEVO-347)
=> fix: add linebreak

.github/workflows/docker-env-release.yml, .github/workflows/npm-build-semantic-version.yml, .github/workflows/npm-docker-build.yml
Disable any release actions for M1
=> chore: M1 Code freeze

.github/workflows/npm-codescan-complete.yml
This PR is based on #24 
I tried to rename compare branch then it automatically closed...
* [DEVO-403](https://htw-cloud.atlassian.net/browse/DEVO-403)
=> DEVO-403 add node versions input and cache feature at npm codescan

.github/workflows/npm-codescan-complete-v2.yml, .github/workflows/yarn-codescan-complete.yml
=> test: change npm and yarn defaults

.github/workflows/api-tests-service.yml, .github/workflows/docker-env-release-api-tests.yml, .github/workflows/docker-env-release.yml
=> [For Testing] Test/api tests GitHub actions new workflow

.github/workflows/api-tests-service.yml, .github/workflows/docker-env-release-api-tests.yml
New API Tests Github Workflow
Test file to test out the new workflow.  
=> Test Update to use working_dir instead

.github/workflows/docker-env-release-api-tests.yml
=> Test/api tests GitHub actions

.github/workflows/docker-env-release-api-tests.yml
**Testing the api test workflow** 
* Added a boolean flag if we want to run the tests are not
* Defaults to false so that it won't break existing repos
=> Add a flag to check whether or not to run the tests

.github/workflows/db-docker-image.yaml, .github/workflows/node-build-docker.yml
=> Tag docker images chain

.github/workflows/api-tests-service.yml
* [VID-181](https://htw-cloud.atlassian.net/browse/VID-181)
[VID-181]: https://htw-cloud.atlassian.net/browse/VID-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VID-181 refactor api-tests-service.yml

.github/workflows/node-build-docker.yml, .github/workflows/npm-codescan-complete.yml
=> Test matrix error

.github/workflows/eks-env-release-test.yml
=> chore: always replace

.github/workflows/eks-env-release-test.yml
=> tweak release

.github/workflows/eks-env-release-test.yml
=> test: enforce auth toggle

.github/workflows/python-codescan.yml
….xml file.
- [x ] 버그 수정 / Bugfix / Corrección de Error
=> Fix Python sonarcloud coverage (python scan)

.github/workflows/python-codescan.yml
- [ x] 개선/최적화 / Enhancement/optimization / Mejora/optimización
If not specified use the default matrix python 3.10 & 3.11.
Allow the caller to specify the Python version, it the want.
Format must be a string, i.e.  '["3.11"]'.
=> Py scan allow to pass in matrix inputs

.github/workflows/node-build-docker.yml
=> DEVO-1499: adding NODE_OPTIONS

.github/workflows/generate-build-text-file.yml, .github/workflows/upload-build-text-file-to-s3.yml
=> add fix build info and uplaod to s3

.github/workflows/docker-release-build.yml, .github/workflows/eks-env-deploy-release.yml
=> fix release pipeline

.github/workflows/eks-env-deploy-release.yml
=> made changes

.github/workflows/static-analysis-manual.yml, .github/workflows/static-analysis.yml
* [AN-1325](https://hanwhavision.atlassian.net/browse/AN-1325)
1. static-analysis-manual.yml 
Example of usage static-anaylsis.yml
2. static-analysis.yml
Github action script for actual static analysis
[AN-1325]: https://hanwhavision.atlassian.net/browse/AN-1325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add static analysis action

.github/workflows/npm-build-semantic-version.yml
=> Fixed conditional if statement

.github/workflows/static-analysis-manual.yml, .github/workflows/static-analysis.yml
=> modify static analysis script

.github/workflows/zip-and-upload-to-s3.yml
=> DEVO-1620: adding file to zip and upload to S3

.github/workflows/zip-and-upload-to-s3.yml
=> DEVO-1620: adding zip and upload file

.github/workflows/eks-env-deploy-release-portal.yml
=> add fix portal release fix

.github/workflows/eks-env-deploy-graphql-release.yml
=> add fix graphQl pipeline

.github/workflows/npm-build-semantic-version-v2
To support migration described in [AN-3429](https://hanwhavision.atlassian.net/browse/AN-3429)
* [AN-3429](https://hanwhavision.atlassian.net/browse/AN-3429)
[AN-3429]: https://hanwhavision.atlassian.net/browse/AN-3429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AN-3429 add package manager agnostic build semantic version workflow

.github/workflows/node-build-docker-v2.yml
- part of [AN-3429](https://hanwhavision.atlassian.net/browse/AN-3429)
- current workflow file doesn't support package manager other than yarn
* [AN-3429](https://hanwhavision.atlassian.net/browse/AN-3429)
[AN-3429]: https://hanwhavision.atlassian.net/browse/AN-3429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AN-3429]: https://hanwhavision.atlassian.net/browse/AN-3429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Create node-build-docker-v2.yml to support pnpm

.github/workflows/npm-build-semantic-version-v2.yml
=> fix:  npm-build-semantic-version-v2.yml node version expects string array

.github/workflows/node-build-docker-release-v2.yml, .github/workflows/node-build-docker-release.yml, .github/workflows/node-build-docker-v2.yml, .github/workflows/node-build-docker.yml, .github/workflows/npm-codescan-complete.yml, .github/workflows/npm-docker-build.yml
=> feat: edit node version

.github/workflows/npm-codescan-complete-no-sonar.yml
=> chore: create new workflow for node scan without sonnar

.github/workflows/eks-env-release-test.yml
=> feat: add exception

.github/workflows/npm-codescan-complete.yml
=> feat: add new token cicd

.github/workflows/node-build-docker.yml
=> Kdog add token for flexai device service2

.github/workflows/node-build-docker-release.yml
=> feat: add anotation

.github/workflows/npm-build-semantic-version.yml
=> feat: edit cicd
